# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  cloud:
    region: bru-2
    clusterId: a26cb4a6-e0c0-40b1-ae07-fe15ea1baf5c
    clientId: ZLF6N_4E-7.76DYAsvN.y1F8j6jIhl0w
    clientSecret: 0NuygsDHVoc5BaB1MF483dDGkdGVJtNwN-ZeE_9Qsg7mGXLRkZaNVWVWBfxXE4Ze
	